# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0LNC3ETs4VEalQ9txQKeu0OUeiG2xxu
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# -----------------------------
# 1. Load Dataset
# -----------------------------
df = pd.read_csv("train.csv")

# Select useful features
features = ['GrLivArea', 'BedroomAbvGr', 'FullBath', 'TotRmsAbvGrd']
target = 'SalePrice'

X = df[features]
y = df[target]

# -----------------------------
# 2. Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------------
# 3. Scaling
# -----------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# -----------------------------
# 4. Linear Regression Model
# -----------------------------
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# -----------------------------
# 5. Predictions
# -----------------------------
predictions = model.predict(X_test_scaled)

# -----------------------------
# 6. Model Evaluation
# -----------------------------
mse = mean_squared_error(y_test, predictions)
rmse = mse ** 0.5

print("Model Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print("RMSE:", rmse)